### ISSUE TITLE
[vote] Process for getting user references 

### ISSUE THREAD

**Issue by dhmlau** [loopbackio/loopback-governance#13]
## Background 
We have been getting user references via [this github issue](https://github.com/loopbackio/loopback-next/issues/3047). The general process is to either post a message there or email me. 

Towards the end of the year, @achrinza suggested to better document this user reference process, so that everyone (users and maintainers) know how to proceed.

There are mainly two things we're looking for user/company who would like to showcase their company in our web site because of their LoopBack usage. 
1/ company logo to put on the main page "Who's using LoopBack?" section
2/ Optionally, a few sentences about their usage and experience with LoopBack - to be added in https://loopback.io/what-our-users-say.html. 

## Proposal 
So far, we've been having good experience with the community in getting their reference. I'm thinking whether it would be even better to ask them to submit PRs to update our web site with their references. As maintainers would still be the ones who're approving (and rejecting) the PR, we can do our own validations.

**Comment by achrinza** [comment]
+1 To document this process in this repo for consistency.

> I'm thinking whether it would be even better to ask them to submit PRs to update our web site with their references. 

I think this can be done, though we should be open to assisting them in creating the PR if necessary.
