### ISSUE TITLE
[OpenJSF] Update / Create Code of Conduct

### ISSUE THREAD

**Issue by dhmlau** [loopbackio/loopback-governance#17]
The main repo loopback-next has [code of conduct md file](https://github.com/loopbackio/loopback-next/blob/master/docs/CODE_OF_CONDUCT.md), but not all repos in [loopbackio org](https://github.com/loopbackio) has it. 

## Acceptance Criteria
Use https://github.com/loopbackio/loopback-next/blob/master/docs/CODE_OF_CONDUCT.md as the reference to add code of conduct for all repos.

- [x] loopback-next
- [x] strong-soap https://github.com/loopbackio/strong-soap/pull/356
- [x] loopback4-example-shopping - PR: https://github.com/loopbackio/loopback4-example-shopping/pull/1466
- [x] loopback.io https://github.com/loopbackio/loopback.io/pull/1325
- [x] loopback-connector-postgresql - PR: https://github.com/loopbackio/loopback-connector-postgresql/pull/495
- [x] loopback-ibmdb https://github.com/loopbackio/loopback-ibmdb/pull/88
- [x] loopback-connector-mongodb - PR: https://github.com/loopbackio/loopback-connector-mongodb/pull/660
- [x] starter https://github.com/loopbackio/starter/pull/2
- [x] loopback-connector https://github.com/loopbackio/loopback-connector/pull/193
- [x] loopback-connector-mssql https://github.com/loopbackio/loopback-connector-mssql/pull/243
- [x] loopback-datasource-juggler https://github.com/loopbackio/loopback-datasource-juggler/pull/1911
- [x] loopback-connector-grpc https://github.com/loopbackio/loopback-connector-grpc/pull/18
- [x] loopback-connector-kv-extreme-scale https://github.com/loopbackio/loopback-connector-kv-extreme-scale/pull/29
- [x] loopback-connector-mysql https://github.com/loopbackio/loopback-connector-mysql/pull/463
- [x] loopback-connector-rest https://github.com/loopbackio/loopback-connector-rest/pull/160
- [x] loopback-connector-openapi https://github.com/loopbackio/loopback-connector-openapi/pull/24
- [x] loopback-connector-sqlite3 https://github.com/loopbackio/loopback-connector-sqlite3/pull/47
- [x] loopback-connector-dashdb https://github.com/loopbackio/loopback-connector-dashdb/pull/104
- [x] loopback4-extension-grpc https://github.com/loopbackio/loopback4-extension-grpc/pull/46
- [x] loopback-connector-cassandra https://github.com/loopbackio/loopback-connector-cassandra/pull/96
- [x] loopback-connector-soap https://github.com/loopbackio/loopback-connector-soap/pull/121
- [x] loopback-connector-couchdb2 https://github.com/loopbackio/loopback-connector-couchdb2/pull/86 
- [x] loopback-connector-db2 https://github.com/loopbackio/loopback-connector-db2/pull/158
- [x] strong-error-handler https://github.com/loopbackio/strong-error-handler/pull/96
- [x] loopback-connector-ibmi https://github.com/loopbackio/loopback-connector-ibmi/pull/23
- [x] explorer.loopback.io https://github.com/loopbackio/explorer.loopback.io/pull/11
- [x] loopback-connector-cloudant https://github.com/loopbackio/loopback-connector-cloudant/pull/250
- [x] loopback-connector-kv-redis https://github.com/loopbackio/loopback-connector-kv-redis/pull/60
- [x] loopback4-example-kafka https://github.com/loopbackio/loopback4-example-kafka/pull/7 
- [x] loopback-connector-oracle https://github.com/loopbackio/loopback-connector-oracle/pull/211
- [x] loopback-connector-elastic-search https://github.com/loopbackio/loopback-connector-elastic-search/pull/142
- [x] loopback-connector-redis https://github.com/loopbackio/loopback-connector-redis/pull/63

**Comment by achrinza** [comment]
Awaiting domain transfer to the OpenJS Foundation and creation of `@loopback.io` emails.

**Comment by dhmlau** [comment]
Got the email aliases: 
- security reporting: `security@loopback.io`
- general: `tsc@loopback.io`

**Comment by achrinza** [comment]
The [onboarding checklist](https://github.com/loopbackio/loopback-governance/issues/16) specifically states:

>  Update project CoC reporting methods to include OpenJS Foundation escalation path

The [OpenJS Foundation's Code of Conduct](https://github.com/openjs-foundation/cross-project-council/blob/8874993a95ab9511efb43e4eb61b71485db6ce19/CODE_OF_CONDUCT.md#escalate-an-issue) is amended to contain additional info, which includes mentioning the escalation path:

> ## Escalate an issue
> 
> The OpenJS Foundation maintains a [Code of Conduct Panel (CoCP)](https://github.com/openjs-foundation/cross-project-council/blob/HEAD/FOUNDATION_CODE_OF_CONDUCT_REQUIREMENTS.md#code-of-conduct-panel). This is a foundation-wide team established to manage escalation when a reporter believes that a report to a member project or the CPC has not been properly handled.
> 
> In order to escalate to the CoCP, email <coc-escalation@lists.openjsf.org>.

There's also other sections such as commitments of CoC report recipients.

Do we need to include these sections in our Code of Conduct as well?

**Comment by dhmlau** [comment]
@achrinza, apologies that I didn't see your above comment after landing all the PRs :(  
I created PR https://github.com/loopbackio/loopback-next/pull/8422 for loopback-next as the template. If you approve, I can propagate it to the rest of the repos.

**Comment by dhmlau** [comment]
All updated. Closing as done. 🎉
