### ISSUE TITLE
Update/add SECURITY.md in repos

### ISSUE THREAD

**Issue by dhmlau** [loopbackio/loopback-governance#24]
Related to https://github.com/loopbackio/loopback-governance/issues/16

- [x] loopback-next https://github.com/loopbackio/loopback-next/pull/8448
- [x] strong-soap  https://github.com/loopbackio/strong-soap/pull/392
- [x] loopback4-example-shopping  https://github.com/loopbackio/loopback4-example-shopping/pull/1486
- [x] loopback.io  https://github.com/loopbackio/loopback.io/pull/1332
- [x] loopback-connector-postgresql  https://github.com/loopbackio/loopback-connector-postgresql/pull/497
- [x] loopback-ibmdb  https://github.com/loopbackio/loopback-ibmdb/pull/90
- [x] loopback-connector-mongodb https://github.com/loopbackio/loopback-connector-mongodb/pull/662 
- [x] starter  https://github.com/loopbackio/starter/pull/4
- [x] loopback-connector  https://github.com/loopbackio/loopback-connector/pull/199
- [x] loopback-connector-mssql  https://github.com/loopbackio/loopback-connector-mssql/pull/245
- [x] loopback-datasource-juggler https://github.com/loopbackio/loopback-datasource-juggler/pull/1922
- [x] loopback-connector-grpc https://github.com/loopbackio/loopback-connector-grpc/pull/20
- [x] loopback-connector-kv-extreme-scale  https://github.com/loopbackio/loopback-connector-kv-extreme-scale/pull/31
- [x] loopback-connector-mysql https://github.com/loopbackio/loopback-connector-mysql/pull/465
- [x] loopback-connector-rest https://github.com/loopbackio/loopback-connector-rest/pull/162
- [x] loopback-connector-openapi  https://github.com/loopbackio/loopback-connector-openapi/pull/26
- [x] loopback-connector-sqlite3  https://github.com/loopbackio/loopback-connector-sqlite3/pull/49
- [x] loopback-connector-dashdb https://github.com/loopbackio/loopback-connector-dashdb/pull/106
- [x] loopback4-extension-grpc  https://github.com/loopbackio/loopback4-extension-grpc/pull/48
- [x] loopback-connector-cassandra  https://github.com/loopbackio/loopback-connector-cassandra/pull/98
- [x] loopback-connector-soap  https://github.com/loopbackio/loopback-connector-soap/pull/123
- [x] loopback-connector-couchdb2  https://github.com/loopbackio/loopback-connector-couchdb2/pull/88
- [x] loopback-connector-db2  https://github.com/loopbackio/loopback-connector-db2/pull/160
- [x] strong-error-handler  https://github.com/loopbackio/strong-error-handler/pull/98
- [x] loopback-connector-ibmi  https://github.com/loopbackio/loopback-connector-ibmi/pull/25
- [x] explorer.loopback.io  https://github.com/loopbackio/explorer.loopback.io/pull/13
- [x] loopback-connector-cloudant  https://github.com/loopbackio/loopback-connector-cloudant/pull/252
- [x] loopback-connector-kv-redis  https://github.com/loopbackio/loopback-connector-kv-redis/pull/62
- [x] loopback4-example-kafka  https://github.com/loopbackio/loopback4-example-kafka/pull/9
- [x] loopback-connector-oracle  https://github.com/loopbackio/loopback-connector-oracle/pull/213
- [x] loopback-connector-elastic-search  https://github.com/loopbackio/loopback-connector-elastic-search/pull/144
- [x] loopback-connector-redis https://github.com/loopbackio/loopback-connector-redis/pull/65

**Comment by achrinza** [comment]
Closing as done.
